const fs = require('fs')
const path = require('path')
const s = fs.readFileSync(path.join(process.env.TEMP, 'tw-index.js'), 'utf8')
const i = s.indexOf('function A(')
console.log('A idx', i)
console.log(s.slice(i, i + 1800))
const j = s.indexOf('invoiceType:')
console.log('\n==== order normalize around invoiceType ====')
console.log(s.slice(j - 900, j + 700))
const k = s.indexOf('Ot={draft')
console.log('\n==== statuses ====')
console.log(s.slice(k, k + 400))
const m = s.indexOf('name:')
console.log('\n==== customer around name field search ====')
const idx = s.indexOf('{id:e.id')
console.log('id:e.id', idx)
console.log(s.slice(Math.max(0, idx - 200), idx + 800))
